# Replicate Netlify build stages
stages:
  - initialize
  - build
  - deploy
  - cleanup
  - post-processing


"Deploy Web Page":
  trigger:
    include:
      - local: '/.gitlab/.gitlab-ci-deploy-web-page.yml'
    strategy: depend
  rules:
    - if: $CI_COMMIT_TAG == null 
      changes:
        - .gitlab/.gitlab-ci-deploy-web-page.yml
        - .gitlab-ci.yml
    - when: never